### ISSUE TITLE
Audio level not shown for audio playback

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#102]
Select Admin Menu.
Select Audio Recorder.
Select an audio recording to start playback.
Expected behaviour: audio playback level indicated by meters.
Actual behaviour: audio player not connected to level meters.

**Comment by jofemodo** [comment]
Update and test, please ;-)

**Comment by jofemodo** [comment]
Eooo! Can you test this? Thanks ...

**Comment by riban-bw** [comment]
Works fine - thanks.
