### ISSUE TITLE
Midi Profile needs UI restart

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#105]
I haven't tested with the latest build. I am in concert mode and won't update.
I have 2 Midi Profiles with midi rules.
When I change the profile, it is only taken into account, when i restart the UI

**Comment by mheidt** [comment]
Even on an updated image, this bug still occurs.

**Comment by jofemodo** [comment]
Do you change the MIDi profile from webconf or from UI?
I just tested with a Gorgona Omega totally updated and it worked for me when changing from both but when using rules, then i noted that rule table is not conrrectly reseted when changing and rules remain from a MIDI profile to another. Could you confirm this behaviour as your problem?

**Comment by jofemodo** [comment]
I just commited some changes that should solve the "rules reseting" problem.

**Comment by jofemodo** [comment]
**NOTE:** MIDI-learning could do strange things when deleting or adding the profile's script rules. 
You have to think that native MIDI learning is implemented using rules that sometimes are chained when learning, so deletig or adding new rules could change the MIDI-learning map.

**Comment by mheidt** [comment]
I can confirm,that it  works for me now.
What about saving the midi profile in the snapshot as well?

**Comment by jofemodo** [comment]
I like the idea of saving MIDI profile inside snapshots.
Please, open a new task for that ;-)
