### ISSUE TITLE
Setting QMidiNet in UI has no effect

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#109]
- Navigate to Admin menu
- Toggle QMidiNet setting
- Restart UI
Expected behaviour: QMidiNet setting is retained.
Actual behaviour: QMidiNet setting returns to previous value.

It seems like this setting may only be set from the web-conf.

**Comment by jofemodo** [comment]
Yes. Currently Qmidinet flag status is not saved when modified from UI.
But it works! Aka, QMidiNet is correctly started/stopped.

**Comment by jofemodo** [comment]
I made "MIDI Network" option to be persistent (saved in MIDI profile) when changing from UI.
BTW, 2 new MIDI options were added to UI's Admin menu (also persistent!):

 - midi_prog_change_zs3
 - preset_preload_noteon

**Comment by jofemodo** [comment]
Test this, please ;-)

**Comment by riban-bw** [comment]
The state is now persistently changed by UI. I don't use MIDI Network so assume it continues to work as expected.
