### ISSUE TITLE
Fails to connect audio to I2S output if USB soundcard inserted during boot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#114]
- Configure Zynthian to use I2S audio interface, e.g. Hifiberry Dac+ Light
- Plug class compliant USB audio interface to USB port
- Boot Zynthian
Expected behaviour: Audio routed to I2S audio interface.
Actual behaviour: Audio routed to USB audio interface.

**Comment by jofemodo** [comment]
Yes. I've tried lot of times to force the correct ordering of audio devices, but with no luck. It seems to not work or i'm not understanding the ALSA documentation, etc.

The issue also prevents Zynthian to work correctly when booting with several USB controllers plugged in. This is, from my POW, much more important for most of use-cases.

**Comment by jofemodo** [comment]
I think this is solved by using explicit device names on jack configuration instead of device numbers.
