### ISSUE TITLE
Engines may buzz when being removed

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#118]
If an engine is creating audio when it is removed from a layer then JACK continues to send audio to the output for a while resulting in a buzz on the output. It would be advantageous to mute the engine or unroute it from output before destroying the engine.

**Comment by wyleu** [comment]
Good Observation

**Comment by jofemodo** [comment]
Could you test this?

**Comment by riban-bw** [comment]
Yes, I tested when I saw the issue was closed and it seems to work nicely thanks. It would be good to have a resolved state for issues, i.e. issue is fixed awaiting test. We would expect the original reporter to test and close issue. I'm not sure how best to implement that in GitHub.

**Comment by jofemodo** [comment]
The canvas rules ;-)
We have "testing" and "Done" columns ;-)
