### ISSUE TITLE
Adjusting encoder 1 in any page adjusts volume

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#121]
Adjusting the first rotary encoder seems to adjust the volume of an instrument but this is not reflected in the engine's parameter page.

**To Reproduce**
1. Add an ZynAddSubFX engine, e.g. Organ 1
2. Adjust the volume to 100
3. Navigate to Admin menu
4. Rotate encoder 1
Expected behaviour: Nothing changes
Actual behaviour: Volume is adjusted
5. Navigate to engine parameter page
Expected behaviour: Volume level matches current volume (as adjusted by encoder 1 in step 4)
Actual behaviour: Volume level remains at 100. Adjusting encoder 1 causes jump of volume to 100.

This is actually true of whichever parameter encoder 1 is controlling, e.g. click encoder 4 to select "mode" page of parameters and repeat test - controller 1 now controlling "drum on/off".

**Setup:**

- Aruk RC-1 2019-05-17-zynthianos-stretch-lite-1.0.0
- RPi3B+, I2S PCM5102A DAC Hifiberry DAC+ Light, HDMI displa, I2C HWC
- zyncoder: master (f672128)
- zynthian-ui: master (3ae0262)
- zynthian-sys: master (92a6093)
- zynthian-data: master (6712b1c)
- zynthian-webconf: master (cca23d2)
- No USB MIDI devices connected

**Additional context**
I found this when I wanted to adjust the volume and intuitively rotated encoder 1. It may be a desirable feature to allow volume adjustment from any screen but the current implementation is flawed and this is not documented.

**Comment by jofemodo** [comment]
Hi @riban-bw !
I just committed a fix for this. I'm keeping the current behaviour, but keeping refreshed the UI values when returning to the control screen.
