### ISSUE TITLE
CUIA up/down seem wrong way round

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#123]
There are CUIA for SELECT_UP and SELECT_DOWN that appear to drive the menu selectino in the opposite direction to that expected.

**To Reproduce**
1. Run python3
2. import liblo
3. liblo.send(('localhost',1370), 'SELECT_DOWN')
3. 

**Expected behaviour**
Menu cursor moves down one position.

**Actual behaviour**
Menu cursor moves up one position.

Nightly build 2019-05-17-zynthianos-stretch-lite-1.0.0 updated on 22/05/2019.

**Comment by jofemodo** [comment]
Internally the UI use "up" for going down because the row index goes up and "down" for going up becasue the row index goes down. Anyway, it can be confuse for a public API like the CUIA, so i will change the behaviour.
