### ISSUE TITLE
Add a base path "/CUIA/" to OSC API

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-ui#125]
https://discourse.zynthian.org/t/is-there-any-zynthian-api/1926/26

**Comment by riban-bw** [comment]
Ha! Didn't even have a change to submit a feature request before you had progressed this through most of its life!!! (I will have to change that test case now...) Cheers!

**Comment by riban-bw** [comment]
I have tested this and it works as expected, thanks. I note that there is currently a limit to two elements in the OSC path. We may wish to reconsider this constraint as we expand OSC support, e.g. a typical OSC to MIDI bridge may use path elements for message type, channel, value, etc. I wonder what benefit the maximum element constraint gives us?
