### ISSUE TITLE
MIDI Recorder doesn't display Recorder files

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#128]
**As A** Zynthian User
**I want to** see a selectable list of recorderd MIDI files
**So That** I can Playback a MIDI File I have recorded.

The Admin MIDI recorder function records and stops but no list of recorded files is displayed, similarly to the Audio Recorder.

**Comment by mheidt** [comment]
I couldn't reproduce this.
But there is a different bug. Did you check the loop checkbox?

/usr/local/bin/jack-smf-player -s -t -l -a ZynMidiRouter:seq_in /zynthian/zynthian-my-data/capture/jack_capture_01.mid 
Jun 03 19:21:10 zynthian startx[13834]: /usr/local/bin/jack-smf-player: invalid option -- 'l'

**Comment by mheidt** [comment]
or I don't have the right version of jack-smf-player...

https://github.com/zynthian/jack-smf-utils

**Comment by wyleu** [comment]
Works on the all machines now. 
@mheidt do you mind if I close?

**Comment by mheidt** [comment]
Sure.
