### ISSUE TITLE
Buzz during reboot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#134]
If Zynthian is rebooted whilst producing sound then a buzzing sound is emitted.

**To Reproduce**
1. Play a note and sustain
2. Reboot Zynthian from webconf

**Expected behaviour**
Audio output mutes before reboot.

**Actual behaviour**
Audio output buzzes until reboot.

**SOFTWARE**
zyncoder: master (f672128) 
zynthian-ui: master (ac000fb) 
zynthian-sys: master (3597e65) 
zynthian-data: master (676c32a) 
zynthian-webconf: master (2904617)

A[ similar issue](https://github.com/zynthian/zynthian-ui/issues/118) has previously been resolved, maybe for UI restarts.

**Comment by jofemodo** [comment]
This should be fixed ;-) Please, try to reboot/shutdown from zynthian UI and also from webconf.
