### ISSUE TITLE
Save "Single Channel Mode" with snapshot / MIDI profile

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#139]
There are different scenarios where I need single channel mode enabled or disabled. It would be advantageous to me to be able to restore a session with this mode set correctly, e.g. I may have a snapshot which I use with multiple instruments / MIDI channels for multi-timbral effect and another snapshot where I want to quickly swap between engines from the same MIDI controller.

I would like for the "single channel mode" status to be saved with the snapshot and probably with the MIDI profile.

**Comment by jofemodo** [comment]
This is probably adressed on #113 ...
