### ISSUE TITLE
Audio routing doesnt get saved correctly in snapshots

### ISSUE THREAD

**Issue by score100** [zynthian/zynthian-ui#147]
This happens when you have minimum 2 layers with each one or more effects on it and save a snapshot. More likely (?) to happen when you have more layers with fx. When being loaded as a snapshot they will play no sound. If looked at layer options from the layers there is no cross on either system or the attached effect.

**To Reproduce**
1. Create 2 layers.
2. Add an effect (I use zynverb) to each of them, save snapshot
3. Power off, and power on. Load snapshot.
4. Play some notes and hear no audio. Looking at the audio routing you can see it ain't routed to nowhere.

**Expected behavior**
You'd expect the zynthian to save the way audio is routed as well.

**Setup:**
Using Aruk RC-3. Last update 8 days earlier.

**Additional context**
This one is kinda tricky as it happened multiple times to me while preparing for a concert. Sometimes all layers get disconnected. Sometimes only one.

**Comment by Arxi** [comment]
Can confirm this issue, and I'm unable to route the audio manually either - it seems like the audio effects in a layer get disconnected, or maybe it's better to say unchained. @score100 have you been able to find a reliable way to "re-set" the layer audio routing to intended state after snapshot is loaded, at least manually??

**Comment by score100** [comment]
@Arxi  so far I could do so manually by using the layer options. 
Generally this one is kind of difficult to reproduce. I had it also sometimes not happening at all. Then again a few times in a different way, where a new layer would be automatically connected to an exisiting effect.

**Comment by jofemodo** [comment]
I've commited some fixes tat should solve the probles. Please, update software and test ;-)

**Comment by Arxi** [comment]
@jofemodo from what I've tested so far, seems like the audio is now routed correctly after the snapshot is loaded. Great job, and thank you very much!

**Comment by Arxi** [comment]
@jofemodo  I managed to come across this bug again - see the attached .zss file. When I load this snapshot, sometimes the audio is not routed anywhere (no sound); sometimes it is routed correctly, but when I leave the Control view and go to layer list, the effects are suddenly bypassed and the synth itself is "reset" to its default values.

It might be connected to the way I created this snapshot: I created 6 layers one by one, each on its own midi channel. Then I deleted the first 5 layers, leaving only the layer 6. Then I tried to move the layer 6 to midi channel 1 - I wasn't able to get any sound from it afterwards (sending notes on channel 1 from sequencer of course), so I moved it back to midi channel 6.

I have the latest updates (updated just now).

[007-1.2-Trip.zss.zip](https://github.com/zynthian/zynthian-ui/files/3648430/007-1.2-Trip.zss.zip)

**Comment by Arxi** [comment]
Hmm. Seems like the synth reset thing might be a separate issue. When I create a new clean MDA JX10/Soft E.Piano layer, change sam parameters and then go back, the parameters are reset to their defaults.

**Comment by jofemodo** [comment]
The problem when moving a layer to a different MIDI channel should be fixed now ...

**Comment by Arxi** [comment]
I updated to the latest version, but now it's kinda hard to test - while loading my older snapshots, most of them say e.g. `JV/MDA JX10 > NoBank` and look like no preset is even selected. When I select a preset, the audio rouitng is incorrect, too. Or should I recreate the snaphots again with latest updates?

**Comment by Arxi** [comment]
So I created a new snapshot, very minimal, just to test the audio routing. Saved, loaded. Audio isn't routed anywhere. Here's the snapshot:
[013-1.3-Vianocka.zss.zip](https://github.com/zynthian/zynthian-ui/files/3719267/013-1.3-Vianocka.zss.zip)

**Comment by jofemodo** [comment]
Hi @Arxi !
Could you try this snapshot?

[014-Jofenocka.zip](https://github.com/zynthian/zynthian-ui/files/3725236/014-Jofenocka.zip)

Regards,

**Comment by jofemodo** [comment]
Regarding your "Vianocka" snapshot, there are 2 problems:
+ We have reorganized Dexed (and other LV2 plugins) presets in banks, so the you have to re-select the bank & preset and save snapshot again.
+ The layer is in ch#5 and "single channel mode" is disable (FYI, MIDI profile options are now saved/restored with snapshots), so perhaps this is the "routing problem".

Regards,

**Comment by jofemodo** [comment]
Hi @Arxi !
I think i've fixed an old problems. Finally i understanded why trying to reuse engine instances between snapshots is failing. I've disabled this "optimization" until i can write a better algorithm for it.
I hope this solves a lot of snapshot-related problems.

The bad part is that snapshots saved after loading several snapshots probably are wrong and should be rebuilt from scratch because routing is broken on them. Broken snapshots can't be recovered easily and i would prefer to not add extra code for recovering these snapshots. Sorry.
