### ISSUE TITLE
Add keyboard functionality to webconf gpio

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#152]
**Is your feature request related to a problem? Please describe.**
The cuia midi functionality for gpio is good but could we add keyboard functions. Audio record could be implemented this way. 
**Describe the solution you'd like**
Drop down to include keyboard function & and appropriate sub values. 
**Describe alternatives you've considered**
I use an external qwerty keyboard to implement record and stop I would prefer to not have this equipment overhear if I have gpio switches available
**Additional context**

**Comment by jofemodo** [comment]
OK @wyleu ! I already understand what you mean. It's done, my friend!! ;-)
