### ISSUE TITLE
Zynthian Audio Play needs Volume Window

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#153]
The Zynthian Admin/Audio Recorder needs a window called "Volume" so the user can set a dedicated volume while an audio file is playing,
Also the user can adress this field to a MIDI-Controller Number to control the volume with an external controller.

**Comment by jofemodo** [comment]
Hi @Mickinator and others!
Please, update your zynthian  and test the "Playback Volume Control".

**Comment by Mickinator** [comment]
Hi Fernando,
great, wonderful❤️

but I cant set a midicontroller
do I something wrong?

von Norbert Schreiber gesendet

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Zynthian Audio Play needs Volume Window 
(#153)
Datum: 05.12.2019, 19:46 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Mention <
mention@noreply.github.com <mailto:mention@noreply.github.com> >

Hi @Mickinator <https://github.com/Mickinator> and others!
Please, update your zynthian and test the "Playback Volume Control".

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/153?email_source=notifications&email_token=ANJNSQKB4RZBBXQRLXIIS2DQXFD7FA5CNFSM4I4YJMS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGBW4TY#issuecomment-562261583> 
, or unsubscribe

**Comment by jofemodo** [comment]
I Norbert! The audio playback volume can't be assigned to MIDI currently.
I will see if i can so something about ... ;-)

**Comment by Mickinator** [comment]
👍

von Norbert Schreiber gesendet

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Zynthian Audio Play needs Volume Window 
(#153)
Datum: 06.12.2019, 23:51 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Mention <
mention@noreply.github.com <mailto:mention@noreply.github.com> >

I Norbert! The audio playback volume can't be assigned to MIDI currently.
I will see if i can so something about ... ;-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/153?email_source=notifications&email_token=ANJNSQIQJ3S2TE5GXDUREPDQXLJPPA5CNFSM4I4YJMS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGFS5QI#issuecomment-562769601> 
, or unsubscribe
