### ISSUE TITLE
Performance Audio-or Miditracks

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#154]
To have a propper gig-performance it should be good to have

- title-storing into snapshot
- volume Window for audio/Midi-track
- transport-buttons for
   - play
   - stop
   - rewind 
(all midi-CC-controllable).

**Comment by mheidt** [comment]
Have you tried to give it a title I the webconf?

**Comment by Mickinator** [comment]
I had a conversation about the transport knobs with jofemodo

**Comment by jofemodo** [comment]
Have you tried to give it a title I the webconf? ;-)

**Comment by jofemodo** [comment]
I added CUIAs for play/stop MIDI & Audio tracks.
Also implemented MIDI System Control messages for MIDI track play/stop.

**Comment by Mickinator** [comment]
Hi Fernando,

what have I to do, to work with this new features?
I can send Note or controller or prgrch- Commands. But what numbers?
Where can I read it?

Thanx for helping!
Micki




Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Performance Audio-or Miditracks (#154)
Datum: 07.10.2019, 16:20 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

I added CUIAs for play/stop MIDI & Audio tracks.
Also implemented MIDI System Control messages for MIDI track play/stop.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/154?email_source=notifications&email_token=ANJNSQPLZUHJL57QYDUZ5CTQNNASNA5CNFSM4I5N7NC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAQQMNI#issuecomment-539035189> 
, or mute the thread

**Comment by jofemodo** [comment]
In the wiki's documentation, my friend ;-)

http://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Controlling_the_UI_with_MIDI_messages

**Comment by Mickinator** [comment]
Wow, that's great.

I only knewed the old one. This evening I have a lot to do!
Thank you so much, my friend 😘🎶🌈






Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Performance Audio-or Miditracks (#154)
Datum: 11.10.2019, 13:52 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

In the wiki's documentation, my friend ;-)

http://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Controlling_the_UI_with_MIDI_messages
<http://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Controlling_the_UI_with_MIDI_messages>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/154?email_source=notifications&email_token=ANJNSQI44QSMGJH4PFMIARTQOBSIHA5CNFSM4I5N7NC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEA7YBIY#issuecomment-541032611> 
, or unsubscribe

**Comment by Mickinator** [comment]
I´ve tried it, but I have no success.
Where are the files I like to play? I see nothing in the Audio Window or in the Webconf Screen.
Where can I choose the wanted song?

**Comment by Mickinator** [comment]
I only see self recorded captures
but no files from the usb-stick

**Comment by jofemodo** [comment]
Volume window is not implemented yet, and it will take some time as it's not a trivial task. Please, be patient.
Regarding the USB-stick, files have to be ".wav" files in the root dir, Files in subdirs will not be shown.
