### ISSUE TITLE
Integrate MIDI-filter plugins in layer's workflow

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-ui#155]
Implement a MIDI-filter chain into layers, allowing to load MIDI filter plugins, and, if possible, mididings scripts.

**Comment by mheidt** [comment]
while you are at it:
When you use a midiprofile that contains spaces in its name, it won't be loaded if you select it via zyntian-ui.

**Comment by jofemodo** [comment]
It's implemented on #243
