### ISSUE TITLE
Audio In needs Control-window

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#157]
Hi Zynthianers,

since I use a behringer uca222 with raspt4 I need an Audio-In-Control-window with

- volume
- expression
- pan
- effects
- small eq

Thanx for helping
Micki

**Comment by Mickinator** [comment]
In addition: I think all engines should receive the controller #7, 11, 64, pan, by default regardless there is a window or not.

**Comment by Mickinator** [comment]
For a first step:
Is it possible to route the Audio-In to Audio-Out and merge with the Zynthian-Sound?

**Comment by jofemodo** [comment]
Of course. Create a new "Effect Layer" and select "Gain 2x2" as engine.

**Comment by Mickinator** [comment]
Did I say that I love you?😂😂😂😂😂

**Comment by Mickinator** [comment]
Is it possible that the Midi-learn-function not works with Gain 2x2?
I cannot adress Ch#15 CC#7 ...

**Comment by jofemodo** [comment]
Master MIDI channel can't be learned, sorry. You have to use a different channel

**Comment by Mickinator** [comment]
Yes, of coarse.
Masterchannel is Ch 16 (1 - 16)
This is Instrument Ch 15




Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Audio In needs Control-window (#157)
Datum: 08.11.2019, 12:27 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, State change <
state_change@noreply.github.com <mailto:state_change@noreply.github.com> >

Master MIDI channel can't be learned, sorry. You have to use a different 
channel

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/157?email_source=notifications&email_token=ANJNSQPHQHGAMJNMKI6CZNLQSVEIRA5CNFSM4I6CJQNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDQRJ7A#issuecomment-551621884> 
, or unsubscribe

**Comment by jofemodo** [comment]
Ups sorry! Seems to be a bug .... let me solve it ;-)

**Comment by jofemodo** [comment]
Ups ... no! It works like a charm for me.
Please, could you describe the problem exactly:
- SD image version
- how did you try to learn
- etc.

**Comment by Mickinator** [comment]
The Prob is soled (nearly).

I do not use the right display driver. I have a
MAKERFACTORY VMP400 Touchscreen-Modul 8.9 cm (3.5 Zoll) 320 x 480 Pixel , not a 
WaveShare 4 GPIO-only. So the touchscreen features don´t work well. Is the WaveShare 4C GPIO-only better? What is the difference?

But I could solve my prob using the mouse.
Now I can control my playbacks from the tablet with the same faders as the kb-sounds.
Won der ful !!!
![14](https://user-images.githubusercontent.com/55761217/68507045-49bb7680-026b-11ea-8c7b-88f25bd6542f.jpg)

**Comment by Mickinator** [comment]
Hi Fernando,
I believe Audio In is only working with 1 channel. Is this possible?
What can I do to hear stereo?

**Comment by jofemodo** [comment]
Currently, each audio input channel is routed to the same output channel.
You can force to mix both channels by including in the "FX chain" a mono-plugin. For instance, the "Gain 1x1" (probably you have to enable the plugin from the webconf).

**Comment by jofemodo** [comment]
Regarding the subject of the issue, i'm implementing a "Mixer" panel that allow to modify the ALSA mixer levels from the UI. Currently it's in the development branch "mixer".

Also this issue is being adressed by #175 ...
