### ISSUE TITLE
UI Freeze after RemoveAll Snapshots

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#164]
I loaded a snapshot with 5 layers successfully.
But when I RemoveAll layers, the UI freezes.

**Comment by mheidt** [comment]
[error.log](https://github.com/zynthian/zynthian-ui/files/3748379/error.log)

**Comment by mheidt** [comment]
The last 3 lines are normal shutdown behaviour:

xinit: connection to X server lost
waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
xinit: unexpected signal 2

**Comment by jofemodo** [comment]
Hi @mheidt !

Could you send a snapshot that reproduce the problem?

Thanks!

**Comment by mheidt** [comment]
Only tonight ..doesn't the error.log print the snapshot as well? Monday, 21 October 2019, 11:55AM +02:00 from Jośe Fernando Moyano  notifications@github.com :

**Comment by mheidt** [comment]
I find it in the dropbox

**Comment by mheidt** [comment]
But I cannot reproduce it anytime anymore.
Try, loading it, BackBackBack.... to LayerList, RemoveAll, Load it Again immediately. (when I pressed RemoveALL twice, the next time worked). BackBackBack... to LayerList, RemoveAll, Freeze
