### ISSUE TITLE
Snapshot Program Change works only with one bank

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#167]
If you have a second bank/folder, the master program change doesn't work anymore

**Comment by mheidt** [comment]
So how are we handling more than 128 snapshots then?
My Kawai uses 2 banks.
We need either a feature of adding more than 128 snapshots into root or we need that bank handling.
I didn't know, that you deactivated the bank feature, btw.

**Comment by mheidt** [comment]
Yes, I knew that.
So the bug is, that if you have two banks, the snapshots won't be loaded anymore.

**Comment by jofemodo** [comment]
It should be workin now

**Comment by jofemodo** [comment]
Update and Try now ;-)
