### ISSUE TITLE
Pianoteq not working

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#170]
Adding a Pianoteq layer does not create any sound when played.

**To Reproduce**
1. Add new Layer - Pianoteq - any instrument
2. Play MIDI keyboard

**Expected behaviour**
Pianoteq instrument plays - audio heard.

**Actual behaviour**
No sound. Other engines do produce sound so MIDI and audio is working.

**Additional info**
ssh to Zynthian shows that Pianoteq has not audio configured. Selecting Jack configuration in Pianoteq GUI allows the engine to start and audio can be produced from the Pianoteq GUI keyboard. MIDI routing is not made to Pianoteq at this point.
Removing and adding Pianoteq engine results in same behaviour, i.e. audio and MIDI are not connected.

I am using nightly build 2019-10-20-zynthianos-buster-lite-1.0.0 on a RPi3 and applied all updates. I am using Pianoteq demo version 6.6.0 as provided by this image.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/67631685-4d292800-f891-11e9-9f0b-2e0313cea938.png)

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Sainsmart 1.8
Wiring: I2C_HWC
SYSTEM
Hostname: zynthian (192.168.1.49 )
OS: Raspbian GNU/Linux 10 (buster)
Memory: 27% (253M/926M)
SD Card: 79% (11G/14G)
MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
QmidiNet: False
TouchOSC: False
SOFTWARE
zyncoder: master (c385e04)
zynthian-ui: master (a56f74b)
zynthian-sys: master (51ea4a2)
zynthian-data: master (f964a46)
zynthian-webconf: master (d2f6290)
LIBRARY
Snapshots: 1
User Presets: 9
User Soundfonts: 0
Audio Captures: 0
MIDI Captures: 0

**Comment by jofemodo** [comment]
It was not detecting the correct version (6.6.0) and generating the config file with a wrong name.
