### ISSUE TITLE
Implement CUIA toggle record function.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#172]
**Is your feature request related to a problem? Please describe.**
In an environment using foot switches to operate Recording/Stop it would be preferable to operate this on one switch.

**Describe the solution you'd like**
The ability to define a specific device switch (or input event) to toggle the record status. 

**Describe alternatives you've considered**
A short press for Record and a long press for top record implements on the I/O pins but this requires implementation of the electrical contacts involved with associated connector choices, and construction.
The USB implementation requires no assembly. 

![](https://discourse.zynthian.org/uploads/default/original/2X/5/52d9486c399eddcc18c83a22b21417341b8acb2d.jpeg)

**Comment by jofemodo** [comment]
It's merged in PR #173

**Comment by jofemodo** [comment]
Also documented in wiki ;-)
