### ISSUE TITLE
Implement an "ALSA Mixer" panel 

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-ui#175]
It could be implemented as "Engine", a kind of "effect" where the controls are the mixer levels.

**Comment by jofemodo** [comment]
It should be remotely accesible by OSC (webconf) and levels should be saved with snapshots.

**Comment by riban-bw** [comment]
This us similar to the idea we were talking about earlier this year of having an effects chain after the engines, like an insert point in a mixer. Also a master mix bus with an effcts chain. With such points in the audio path we can add effects, each with OSC / MIDI control.

**Comment by jofemodo** [comment]
Checkout "mixer" branch ;-)

**Comment by jofemodo** [comment]
MIDI control is very slow because the use of amixer as interface for the ALSA mixer. We should study to use a faster interface.

**Comment by jofemodo** [comment]
A sender poll thread has been implemented for avoiding the "slow" MIDI control problem. Now it works like a charm ...
