### ISSUE TITLE
Allow capture names with single quotes

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#184]
/usr/bin/mplayer -nogui -noconsolecontrols -nolirc -nojoystick -really-quiet -slave -loop 0 -ao jack -input file='/tmp/mplayer-control' '/zynthian/zynthian-my-data/capture/Ain't No Sunshine.mp3'
/bin/sh: 1: Syntax error: Unterminated quoted string

**Comment by jofemodo** [comment]
OK! It's solved!
BTW, webconf capture panel is broken too when using filenames containing quotes ;-)
