### ISSUE TITLE
Program Change 1 shows "MIXER" instead of program / patch name

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#186]
**Describe the bug**
Sending a program change 1 message shows "MIXER" in the title bar. Sending any other program change number shows the name of the patch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Disable Single Channel Mode
2. Select an engine with multiple presets including one for program 1
3. Send Program Change 1 message
4. "MIXER" is displayed in title bar

**Expected behaviour**
Name of preset 1 should be displayed.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: No detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: ???
Memory: 17% (165M/926M)
SD Card: 81% (11G/14G)
Temperature: 53.7ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (15eafb9)
zynthian-sys: master (daf759a)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (9fd249a)

**Comment by jofemodo** [comment]
It's solved in dd960ca
