### ISSUE TITLE
Midi player not playing sleigh bells correct

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#187]
The attached midi file is playing 4th at C4 for 2 minutes. (midi channel 11)

When you assign a linuxsampler/percussion/sleigh bells to layer 11, every 4th note will be swallowed.

**Comment by jofemodo** [comment]
Why channel 11?  Is the problem affecting all channels or only channel 11?

**Comment by mheidt** [comment]
My USB is programmed on channel 11. 
It is a LinuxSampler issue. When I create a ZY layer, it works. Maybe it is only relates to the sleigh bell sound. haven't checked.

**Comment by jofemodo** [comment]
Hi @mheidt !

Do you have extra info about this issue?

Regards,

**Comment by mheidt** [comment]
[sleigh_bells.zip](https://github.com/zynthian/zynthian-ui/files/4188804/sleigh_bells.zip)
Upload the soundfont into the sf2 folder and the mid into the captures.
Load the snapshot on Midi Channel 11.
Run the mid file in a loop. 
You should hear the sleighbells but very slowly. When you crank up to 300bpm, it's near a quarter beat.

**Comment by mheidt** [comment]
maybe the channel 11 wasn't necessary and I created the mid file on channel1 but was running in single layer mode

**Comment by riban-bw** [comment]
MIDI playback is now performed by bespoke Zynthian library. Please retest.
