### ISSUE TITLE
Toggle MIDI & Audio Play option on Keybinding

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#189]
**Is your feature request related to a problem? Please describe.**
Add the ability to assign Audio Play /stop & Midi Play stop to CUIA. 

**Describe the solution you'd like**
Addition of toggle Midi Play letter (n?) & toggle Audio (b?)

**Describe alternatives you've considered**
THe facility exists to Record via toggle. Adding Toggle Play means you can cotrol a zynth rec/playback entirely from a 2 footswitches.

**Additional context**
Status display may need consideration.

**Comment by jofemodo** [comment]
Please, update & test it ;-)
