### ISSUE TITLE
Activate Plugin when in snapshot

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#201]
When you load a snapshot, that contains a plugin, that is not enabled, the following error is shown
ERROR:zynthian_gui_layer: Invalid snapshot: ‘JV/YK Chorus’
Feb 16 12:06:10 zynthian startx[8568]: Traceback (most recent call last):
Feb 16 12:06:10 zynthian startx[8568]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py”, line 720, in load_snapshot
Feb 16 12:06:10 zynthian startx[8568]: engine=self.zyngui.screens[‘engine’].start_engine(lss[‘engine_nick’])
Feb 16 12:06:10 zynthian startx[8568]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py”, line 131, in start_engine
Feb 16 12:06:10 zynthian startx[8568]: info=self.engine_info[eng]
Feb 16 12:06:10 zynthian startx[8568]: KeyError: ‘JV/YK Chorus’

And the snapshot is non responsive after loading.

Better would be if the plugin will be enabled automatically

**Comment by jofemodo** [comment]
Better than enabling a disabled plugin, allow to load a disabled plugin.
Now, disable/enable plugins only affects the list shown by UI when creating a layer. It doesn't limit the plugins that can be loaded from a snapshot.
