### ISSUE TITLE
Fast preset loading in pianoteq does not cover user presets

### ISSUE THREAD

**Issue by hal80** [zynthian/zynthian-ui#204]
**Describe the bug**
There is a bug in loading or changing into pianoteq user presets.
This affects at least pianoteq stage 6.6 version in the most recent (february 4, 2020) zynthian.
User presets can only be properly loaded when they are the first preset to be loaded in pianoteq.
If there was any other of the standard presets loaded before, the custom preset is not loaded correctly: there appears the name of the user preset in the display, but the sound is still from the previously loaded standard preset.
Exception: load standard preset from the last instrument and after that, a user preset. Thus, the he “distance” from presets being loaded is big enough (aka > 127) and user presets load correctly.

**To Reproduce**
0. Create user preset for e.g. Steinway D in native pianoteq gui.
1. Zynthian: Remove all layers
2. Create new pianoteq layer
3. Select standard (non user) preset (e.g. Steinway D) --> loads correctly
4. Select user preset within the same instrument (Steinway D) --> does not load correctly (only name appears, but sound is still from from previous preset).

**Expected behavior**
Step 4 - both displayed name and sound should be from custom preset.

**Setup:**
 - SD-image https://os.zynthian.org/2019-09-24-zynthianos-buster-lite-1.0.0-RC1.zip with latest update from menu "update zynthian"
 - Hardware Config: Raspberry Pi4

See discussion here: 

https://discourse.zynthian.org/t/bug-in-loading-changing-pianoteq-presets/3772

Related: 
Fast preset loading: 

https://discourse.zynthian.org/t/new-features-improved-audio-routing-pianoteq-fast-preset-loading/2326

**Comment by jofemodo** [comment]
It's fixed now. Please, update and test.
