### ISSUE TITLE
Transpose not working

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#205]
I tested on two machines.
The Transpose Layer option doesn't work anymore.

**Comment by jofemodo** [comment]
It works perfectly for me. I can't reproduce. I would need more info about the issue ...

**Comment by jofemodo** [comment]
What other MIDI options are you using?
Could you send me your MIDI profile?

**Comment by mheidt** [comment]
Never test with midi channel 1! :)
Create a layer at midi channel 5 (aka 4).
And transpose it.
In the snapshot file it is
"transpose": [12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

If you change the layer to channel 1, the transpose works.

**Comment by jofemodo** [comment]
It should be fixed now.
