### ISSUE TITLE
Snapshots do not use the edited parameters

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#210]
Hello All, hallo Jose,

if I call a Snapshot using the clone function (clone ch# 1  to ch#2) eg Piano / Strings with Vol 100/25 and save that snapshot, the ch#2 volume is  much to high when I recall that snapshot.

Raspi 4
updated 09.03.20
ch1 = Pianotec Blüthner Vol 100
ch2 = Fluitsynth Strings Vol 25
clone 1 -> 2
save Snapshot

then call another sn and call the Piano/String-Sn again.
Every Time I have to edit the volume parameters again.

Thanks for helping 🌈

**Comment by jofemodo** [comment]
Try now! It should be solved ...

**Comment by Mickinator** [comment]
Hi Jóse,

thank you! It works. You're the best.
Btw. Is there a manual how to work with the mixer?

Have a nice week.
Regards
Norbert




Gesendet mit der Telekom Mail App
<https://www.telekom.de/unterwegs/apps-und-dienste/kommunikation/telekom-e-mail?wt_mc=alias_9998_unterwegs/apps-und-dienste/telekom-email#mail-app>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Snapshots do not use the edited 
parameters (#210)
Datum: 09.03.2020, 20:09 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Try now! It should be solved ...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/210?email_source=notifications&email_token=ANJNSQIIVMDMBGK6ZOSOBFDRGU5E5A5CNFSM4LEPQAR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOIVNSI#issuecomment-596727497> 
, or unsubscribe

**Comment by jofemodo** [comment]
All the documentation is on the Wiki:

https://wiki.zynthian.org

Regarding the Mixer, you can configure the parameters shown on the UI from the webconf:

**Hardware -> Audio -> Mixer Controls -> [+]**

And remember that this is a collaborative project, and you are invited to improve the wiki's documentation. If you want to do it, simply ask me for a wiki account ;-)

Regards,
