### ISSUE TITLE
Can no longer select lv2 patches in patch grroup 'none' 

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-ui#215]
**Describe the bug**
When choosing patches for oxbd and padthv1 I can no longer select patches that are in the group 'None'

**To Reproduce**
1.  add layer obxd or padthv1
2. Choose midi channel
3. Scroll down to group 'None'
4. The cursor will stop at the group above

**Expected behavior**
Scroll to patch group 'None' and allow click

**Setup:**
 - SD-image:  Buster
 - Hardware Config: v2
 - Software Version: 

 zyncoder: master (8759b11)
zynthian-ui: master (527236f)
zynthian-sys: master (e3a2250)
zynthian-data: master (9cccef5)
zynthian-webconf: master (d72a695)

**Comment by jofemodo** [comment]
OK! It's solved! Please, update and test ...

**Comment by Baggypants** [comment]
Test successful!
