### ISSUE TITLE
Route audio from standalone engines to MOD-UI, allowing to use it as FX processsor

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-ui#22]
Route audio from standalone engines to MOD-UI, allowing to use it as FX processsor.

 + mod-monitor can be used as an audio proxy for that
 + MOD-UI should  be modified to add monitor audio inputs in the canvas.
 + Zynthian UI's layer options menu will allow to route/unroute any synth engine to MOD-UI, using mod-monitor or system output.
 + Snaphosts will save the monitor status for every active engine
 + When an engine is destroyed (no more layers using it), the monitor status will be reseted
 + Autoconnector should be modified to use and manage the monitored_engines list

**Comment by jerash** [comment]
very nice feature
