### ISSUE TITLE
Pressing A Key bound to Record stop crashes gui . . .

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#226]
**Describe the bug**
IG a key allocated to Audio Record stop and the machine is not in Record mode. IT will crash with a message  . . . .

ERROR:zynthian_gui_audio_recorder: ERROR STOPPING AUDIO RECORD: 'NoneType' object has no attribute 'communicate'

**To Reproduce**
1. Bind a key to Record stop
2. DO NOT enter record mode
3. PRess bound record stop key
4. See error....

**Expected behavior**
Should have no effect

**Screenshots**

![image](https://user-images.githubusercontent.com/79083/79229221-8e6ebd80-7e5a-11ea-89d2-bd7a57fbcab3.png)

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/79228794-f375e380-7e59-11ea-8a17-7ec5ad9e7f55.png)

**Additional context**
Identifying keys pressed and confirming the function of the key bindings is lacking status. Could a pressed key display be added to the keybind page so you can see which keys are actually being produced ( very useful with strangely mapped devices ( foot switches etc).

The events should also appear in the non debug UI-log as confirmation of successful operation.

**Comment by jofemodo** [comment]
It's solved. Please update and test.
