### ISSUE TITLE
Tkinter exception

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#227]
**Describe the bug**
Starting Zynthian from the command line I observed a repeating error describing a tkinter exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start zynthian from command line

**Expected behaviour**
Zynthian starts without error.

**Actual behaviour**
Zynthian starts but repeatedly shows error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 391, in cb_listbox_release
    dts=(datetime.now()-self.listbox_push_ts).total_seconds()
AttributeError: 'zynthian_gui_control' object has no attribute 'listbox_push_ts'
```

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

SOFTWARE
zyncoder: master (3513de2)
zynthian-ui: feature/stepseq (80fe30c)
zynthian-sys: master (ccad6f8)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
Zynthian starts displaying the 1#BF/Sin > Upper/Booker T Jones preset, main control screen. After changing to show another engine (10#JV/Black Pear 5 > Default) and back, the issue disappeared.  I can't find where _listbox_push_ts_ is defined.

**Comment by jofemodo** [comment]
Although i can't reproduce the error, i've added extra checking for avoiding the race-conditions that cause the issue. It should be fixed now. Please, update and test.
