### ISSUE TITLE
Wrong screen displayed during navigation

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#228]
**Describe the bug**
Under certain navigation scenarios the wrong screen is displayed, e.g. ALSA Mixer instead of Engine control screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create engine, e.g. 1#BF/Sin > Upper/Booker T Jones
2. Navigate to ALSA Mixer screen
3. Bold BACK to go to Main screen
4. Short BACK

**Expected behaviour**
Navigates to engine control screen

**Actual behaviour**
Navigates to engine ALSA Mixer screen

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

 SOFTWARE
zyncoder: master (3513de2)
zynthian-ui: feature/stepseq (0da9e2a)
zynthian-sys: master (ccad6f8)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
This only seems to happen for ALSA Mixer and may be related to other issue where ALSA Mixer shows engine controls when no ALSA mixer controls are available.

**Comment by jofemodo** [comment]
It's solved now. Please update & test.
