### ISSUE TITLE
Program Change does not work as it should

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#229]
If I send a Program Change command Zynthian does't reakt in all situations

*To Reproduce**
My Organs are in Folder 001.
Nr 6 is Jimmy Smith, Nr 7 is John Lord.
If I send MSB H BF 00 01, LSB H BF 20 01, PC H CF 07 it works all well.
If I send MSB H BF 00 01, LSB H BF 20 01, PC H CF 06 Zynthian does not finnish the call. No sound is to hear.

My Midi Options are ser to Master Midi Channel = 16, Master Change Type = Custom, Master Bank Change Mode = MSB.

If tried to send other Combinations of MSB, LSB, PC, but I had no good results. The only stable version to call John Lord is the showed above 1 1 7.

![Screenshot_2020-04-14 Zynthian Configuration](https://user-images.githubusercontent.com/55761217/79224436-5d42bd00-7e5b-11ea-8e6c-8c7a388d75b0.png)

![IMG_2928](https://user-images.githubusercontent.com/55761217/79225125-8f085380-7e5c-11ea-91b4-39b0e46876d7.JPG)

This foto shows, where Zynthian stops
![IMG_2929](https://user-images.githubusercontent.com/55761217/79225136-93347100-7e5c-11ea-8513-d66a3292d268.JPG)

This is a Midi-Ox-Foto.  The first PC doesn work, the secound does.
![IMG_2930](https://user-images.githubusercontent.com/55761217/79225145-962f6180-7e5c-11ea-9faf-0f0e12316960.JPG)

**Comment by jofemodo** [comment]
Can you confirm that your snapshots are working OK when loaded from the UI?

**Comment by Mickinator** [comment]
No, i can't. I was a while only working with the 'John Lord' spapshot and 
changed the snapshots only via midi. Now I see, it's a question of every 
program change.
Via UI and via Midi 1 1 7 is working, 1 1 6 not.

Tomorrow i will send you some snapshots.

Best thanks for your work!




Gesendet mit der Telekom Mail App
<https://www.telekom.de/unterwegs/apps-und-dienste/kommunikation/telekom-e-mail?wt_mc=alias_9998_unterwegs/apps-und-dienste/telekom-email#mail-app>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Program Change does not work as it 
should (#229)
Datum: 14.04.2020, 20:14 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Can you confirm that your snapshots are working OK when loaded from the UI?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/229#issuecomment-613598898> 
, or unsubscribe

**Comment by jofemodo** [comment]
Hi @Mickinator !

Did you advance with this issue? Is the problem still there with latest SD images?

**Comment by Mickinator** [comment]
Hi Jose,
please excuse. Momentary I´ve a lot of trouble with my 85 years old aunt. She is sick with demencial problems and I forgot this issue.

I´ve made a lot of updates in the last time and at one point the prob was solved. 
Please set this issue to solved.

I´ve tried to install the new image to a sd, but after burning my PC says, there is an incorrect checksum and the sd does not work. 
Because the probs with my aunt i didn´t take newer tries.

Keep healthy and thanks for your work !

**Comment by jofemodo** [comment]
Latest official SD image (Buster RC-2) should run like a charm, and also some of the latest nightly builds.
