### ISSUE TITLE
Code review: zynautoconnect_audio calls wrong function

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#231]
**Describe the bug**
During code review I noticed what appears to be an incorrect call.

Within zynthian_gui.py there is the code:

```	def zynautoconnect_audio(self, force=False):
		if force:
			zynautoconnect.midi_autoconnect(True)
		else:
			self.zynautoconnect_audio_flag = True
```

Should this actually call `zynautoconnect.audio_autoconnect`?

**Comment by jofemodo** [comment]
Ups! It's a good catch!! Fixed now!

Thanks a lot!
