### ISSUE TITLE
Change Midi Channel of Pianoteq layer

### ISSUE THREAD

**Issue by hal80** [zynthian/zynthian-ui#235]
If I have just one single synth layer, it's possible to clone it to another midi channel, but there is no option to change the assigned midi channel.
Only if there are more than one layer, it's possible to change their respective midi channel, but still not for the first one.
Is there a certain reason why changing midi channel is not implemented if there is only one layer?
Could it be implemented?
One additional remark: when I have two layers, and remove the first one (the oldest one, without the option to change its midi channel), I'm left with only one layer in the list, i.e. the layer that was created most recently. Then, that single layer **has** an option to change its midi channel.

**Comment by jofemodo** [comment]
I can't reproduce your problem. It works perfectly for me.
What engine are you using for the first layer? Please, remember to specify the steps for reproducing an error when opening an issue. It saves time ;-)

**Comment by hal80** [comment]
How could I forget ;-)
Sorry, in fact it's not the fist layer, but it's the Pianoteq Engine in any layer which has no "change midi channel" option. This is reproducable at any state / configuration the zynthian is in, no matter what other layers exist and what midi channels are used. Maybe its due to licensing, because it can only run in once instance.
(I had initially assumed that the order in which the layers are created plays a role, but actually I was loading Pianoteq as the first layer for most of the time.)
Im running https://os.zynthian.org/2019-09-24-zynthianos-buster-lite-1.0.0-RC1.zip which I have regularly updated.
zyncoder: master (3513de2)
zynthian-ui: master (926af8e)
zynthian-sys: master (ba3d180)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Comment by jofemodo** [comment]
Sorry, currently Pianoteq layers can't be moved to another MIDI channel because the engine have to be started in fixed layer. I will try to study how to improve this ... perhaps making Pianoteq to listen all layers (i think this is possible) and filtering on zynthian.

Regards,

**Comment by jofemodo** [comment]
Hi @hal80 ,

Could you confirm that it works for you?

Thanks!

**Comment by hal80** [comment]
Yes it works! I can change it to other channels and back, and also if there are other midi channels occupied by other layers it works. Thanks for implementation :)
