### ISSUE TITLE
MIDI Timecode causes MIDI input lamp to be permanently on

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#238]
**Describe the bug**
Feeding a stream of MIDI timecode into the MIDI input results in the MIDI input indicator in the topstrap being permanently on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect external MIDI device producing MIDI timecode to MIDI input
2. Play some notes on a MIDI keyboard

**Expected behaviour**
MIDI indicator in topstrap indicates the notes being played by keyboard.

**Actual behaviour**
MIDI indicator in topstrap permanently indicates MIDI timecode being received.

**Setup:**
 HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

SOFTWARE
zyncoder: master (3513de2)
zynthian-ui: master (77fd40b)
zynthian-sys: master (ccad6f8)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
It may be advantageous to indicate MTC with another indicator, e.g. underline the MIDI indicator space and show 'm' when other MIDI data is received, e.g.
![image](https://user-images.githubusercontent.com/3158323/79252498-a1dd5100-7e79-11ea-9f90-2c6a7ef9a36d.png) ![image](https://user-images.githubusercontent.com/3158323/79252466-92f69e80-7e79-11ea-9581-5f4b78003068.png) ![image](https://user-images.githubusercontent.com/3158323/79252513-aace2280-7e79-11ea-8b89-3f70d348a615.png)

**Comment by riban-bw** [comment]
The underscore looks jagged and wrong:
![image](https://user-images.githubusercontent.com/3158323/79680577-152feb80-8209-11ea-87e4-22f7927285f1.png)

**Comment by jofemodo** [comment]
It should be solved now. Please confirm!

**Comment by jofemodo** [comment]
Is it solved now, right?

**Comment by riban-bw** [comment]
No! I just checked out master and see the following behaviour:
- Play a MIDI note: 'm' shows in status - expected behaviour
- Start clock: 'm' with underscore shows in status - unexpected behaviour

Whilst the MIDI clock is running, even without any other MIDI messages occurring, there is a permanent underscored 'm' displayed.

Webconf MIDI monitor shows only SYS CLOCK messages.

**Comment by jofemodo** [comment]
Try now ...

**Comment by riban-bw** [comment]
Thanks! Working now.
