### ISSUE TITLE
Pressing Layer Encoder (TL) in Layer page rotates thro' Layers

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#242]
**Is your feature request related to a problem? Please describe.**
The mechanism employed to switch between layers whilst in Engine mode (press to rotate throu' loaded layers) can be trained from the Layer page by enabling pressing this encoder to cycle through the layers as displayed on this page.

**Describe the solution you'd like**
Simply as above. Short press on Layer encoder walks Layers in LAyer display

**Describe alternatives you've considered**
It's a really small detail

**Additional context**
Expectation of least surprise.

**Comment by jofemodo** [comment]
Conceded!! ;-)
Please, update and test ...
