### ISSUE TITLE
MIDI effect layer

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-ui#243]
We have a Synth layer and an Audio Effect Layer. I think we need a MIDI effect layer for adding in arpeggiator lv2's and the like., This would claim a MIDI channel and clone it's output to other channels where synths would be.

**Comment by jofemodo** [comment]
Yes. I'm thinking about this subject from a time ago, and there is some open proposals regarding this, like:

https://github.com/zynthian/zynthian-ui/issues/155

So, perhaps it's a good moment to step forward and implement it ... ;-)

**Comment by jofemodo** [comment]
It's almost implemented ...

a56c8e9
0144ffb

Those of you wanting to test this new feature, simply select the “midi-chain” branch for UI’s repository. You can use the webconf for that.

Ahhh!, don’t forget to “enable” some MIDI tool plugin from the webconf’s LV2-plugins panel :wink:

**Comment by jofemodo** [comment]
BTW, i enjoyed a lot chaining  MIDI-chord + Arpeggiator
