### ISSUE TITLE
Selecting two audio capture inputs for mono plugin only connects the first

### ISSUE THREAD

**Issue by jypma** [zynthian/zynthian-ui#261]
- Create an Effect layer with a mono LV2 plugin, on a 2-capture channel sound card (e.g. Datasheet DAC+ ADC Pro)
- Default settings select both `capture_1` and `capture_2`, which also shows in the new _Audio Capture_ menu.
![screenshot](https://user-images.githubusercontent.com/483519/85687288-06662900-b6d1-11ea-9e45-e2b4d36dd4e2.jpg)
- However, Only the first one is actually connected:
```
root@zynthian2:~# jack_lsp -c
system:capture_1
   SooperLooper-00:input
system:capture_2
```

Going into _Audio Capture_ and disconnecting `capture_1` will now connect `capture_2` (which is still selected) correctly.

Expected behaviour is that they both are connected, since they both are selected.

**Comment by jofemodo** [comment]
Please, test and confirm if it's fixed.
