### ISSUE TITLE
UI does not return to previous screen if cancel from long press SELECT

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#269]
**Describe the bug**
If you use a shortcut to select a transitory action, e.g. Shutdown, then subsequently cancel that action, you are not returned to the screen you were previously seeing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to a screen, e.g. MIDI Recorder
2. Long press SELECT until Power Off screen displays
3. Press BACK

**Expected behaviour**
Return to previous screen, e.g. MIDI Recorder

**Actual behaviour**
Return to different screen, e.g. Main menu

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

SOFTWARE
zyncoder: master (2703237)
zynthian-ui: feature/stepseq (c7f13dd) (Also occurs with master)
zynthian-sys: master (c74ff3b)
zynthian-data: master (9cccef5)
zynthian-webconf: master (9a80268)

**Additional context**
Sometimes it will return to the engine control screen. This is most objectionable when in an editor like step sequencer and accidentally go to Shutdown (or maybe other shortcut location) then try to return to where you were but instead end up in synth control screen.

**Comment by jofemodo** [comment]
I can't reproduce the issue. It seems to be solved, at less on testing.
