### ISSUE TITLE
Pianoteq internal engine rate hardcoded to potentially inappropriate rate

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#273]
**Describe the bug**
When Zynthian starts pianoteq it updates the pianoteq configuration, setting engine_rate to 22050. This may be a suboptimal value if JACK is running at a samplerate other than 22050, 44100, etc. e.g. 32000, 48000. The pianoteq GUI shows a warning that performance may be degraded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure JACK for samplerate of 32000 and buffer of 256
2. Connect to Zynthian via ssh with x-forwarding enabled
3. Start Pianoteq
4. Open Pianteq preferences and select "Perf" tab
5. Observe Internal sample rate = 22050 and associated warning, "Suboptimal buffer size"

**Expected behaviour**
Pianoteq engine_rate should be set to a suitable value based on JACK sample rate, e.g.

JACK Samplerate | Pianoteq engine_rate
------------ | -------------
8000 | 8000
24000 | 24000
32000 | 16000
44100 | 22050
48000 | 24000
96000 | 24000
192000 | 24000

**Additional context**
It may be preferable for users to be able to select a setting that is optimal for them but this may proved challenging to implement and support. The table above seems like fairly safe figures based on current considerations of RPi performance.

**Comment by jofemodo** [comment]
Already fixed & merged on #270.
