### ISSUE TITLE
Favourite presets do not work in snapshots

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#278]
**Describe the bug**
Engine preset do not restore when loading snapshots if the preset is a favourite.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add synth layer, e.g. setBfree: BF/Sin > Upper/Blues 1
2. Add preset to favourites by bold pressing in the preset list
3. Remove layer - this step seems to be required to cause preset to be fixed in favourites list
4. Add synth layer, selecting the preset previously added to favourites
5. Save same configuration as new snapshot
6. Load newly created snapshot
7. Engine loads but no preset selected.

Note that non-working snapshots have '*' in title of preset.

**Expected behaviour**
Snapshot should load layer and select correct preset.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: Behringer UMC404HD
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09
Memory: 4% (178M/3906M)
SD Card: 38% (10G/28G)
Temperature: 52.0ºC

SOFTWARE
zyncoder: master (9b8de4f)
zynthian-ui: master (bb888fc)
zynthian-sys: master (f398d09)
zynthian-data: master (8b13619)
zynthian-webconf: master (e671cad)

**Additional context**
This _may be related to issue zynthian/zynthian-issue-tracking#234 where user cannot remove preset from favourites.

**Comment by jofemodo** [comment]
This should be solved now.
