### ISSUE TITLE
Cannot remove preset from favourite list

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#279]
**Describe the bug**
Once a preset has been made a favourite for a while it cannot be removed from favourites.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a synth layer, e.g. setBFree
2. Add a preset to favourites by bold press in the preset list (observe that bold press toggles favourite selection)
3. Remove layer
4. Add synth layer
5. Bold press on preset in preset list

**Expected behaviour**
Preset toggles between favourites.

**Actual behaviour**
Preset cannot be removed from favourites.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: Behringer UMC404HD
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09
Memory: 4% (178M/3906M)
SD Card: 38% (10G/28G)
Temperature: 52.0ºC

SOFTWARE
zyncoder: master (9b8de4f)
zynthian-ui: master (bb888fc)
zynthian-sys: master (f398d09)
zynthian-data: master (8b13619)
zynthian-webconf: master (e671cad)

**Additional context**
A (not user friendly) workaround is to remove favourites file (or entry within), e.g. /zynthian/zynthian-my-data/preset-favorites/BF.json.
This has significant impact on snapshot workflow due to issue zynthian/zynthian-ui#278.

**Comment by jofemodo** [comment]
This should be solved now. Please test & confirm
