### ISSUE TITLE
Hardcoded Pianoteq bank list not exhaustive

### ISSUE THREAD

**Issue by sehrgut** [zynthian/zynthian-ui#282]
**Describe the bug**
When Pianoteq instruments are purchased but not in the hardcoded bank list, they show up in the Pianoteq gui, but not in the modui.

**To Reproduce**
1. Add any pianoteq instrument not in the bank list
2. Update Presets from webconf
  - Note this also works if you force update by moving /home/pi/config/pianoteq6/presets_cache.json.
3. Load a new Pianoteq layer
4. Note that the missing instruments are still missing.

**Expected behavior**
If presets that cannot be determined to be part of banks are found, they should be included in the presets list instead of being ignored.

Attached are the output of `pianoteq6 --list-presets` and my presets-cache.json.

[pianoteq-presets-example.zip](https://github.com/zynthian/zynthian-issue-tracking/files/5054728/pianoteq-presets-example.zip)

**Comment by jofemodo** [comment]
dfea2c3
