### ISSUE TITLE
ON Layer MIDI channel change activate the selected MIDI channel on scroll.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#292]
**Is your feature request related to a problem? Please describe.**
If you are changing MIDI channel for a confused controller that doesn't always come up on the same channel ( I'm looking at you Akai MPK Mini ) it can be a bit hit and miss working out which channel something is transmitting on.

If the MIDI channel select is active in the MIDI Channel selction you can quickly see which channel is active and selct accordingly. Otherwise you 
1/ use the webconf to see which channel is transmitting (reqires web browser eleswhere) 
2/ Select and try and then go throu' the menu option to get back to the MIDI channel select dialog.

**Describe the solution you'd like**

The MIDI channel selection dialog makes the change actively so the highlghted selected channel is the channel the layer is responding to.

Back will return to the previous setting select will select the chosen channel

**Describe alternatives you've considered**
1/ use the webconf to see which channel is transmitting (reqires web browser eleswhere) 
2/ Select and try and then go throu' the menu option to get back to the MIDI channel select dialog.

**Additional context**
Helps user expectation...

**Comment by jofemodo** [comment]
Hi @wyleu !

I just implemented this in the best way i found. Please, update and test ...
Note that this only work on poly mode (single active channel mode disabled).

Regards,
