### ISSUE TITLE
Scrolling through pages on the control screen should update controllers as you scroll.

### ISSUE THREAD

**Issue by jhnnhgh** [zynthian/zynthian-ui#296]
**Is your feature request related to a problem?**
Scrolling through the pages with the select knob in the control view of a layer does not show which controllers are available on the selected page until the page is selected. This makes it very hard to find the controller that you are looking for.

**Describe the solution you'd like**
- Simply drawing the controllers as you scroll would solve this problem. They could be greyed out to show that they cannot be changed with the knobs until the page is selected.
- I believe we can find a better place to display the page numbers than using an entire corner of the screen.
- I also can't come up with a reason to keep the zynthian logo while paging.

**Additional context**
This issue ties in closely with   (https://github.com/zynthian/zynthian-ui/issues/86) as it is an improvement to the screen layout.

**Comment by jofemodo** [comment]
Hi @jhnnhgh! I just implemented this. If you have the latest stable SD image (Buster RC-2), simply "update software" and enjoy ...

Regards!
