### ISSUE TITLE
PT Layer disappears

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#298]
- empty layers
- click on PT
- In MIDI channel view, go BACK to LAYERS
- Click New Layer, PT is gone

When you select a MIDI Channel, the layer is created and when removing it, everything is ok.
Removing All Layers resets everything like expected also.

**Comment by jofemodo** [comment]
Hi @mheidt !

I think it's solved and BTW, layer creation workflow has been improved.
Please, update and test.

Thanks!
