### ISSUE TITLE
Display MIDI event info in status region

### ISSUE THREAD

**Issue by smiths73v3** [zynthian/zynthian-ui#300]
**Is your feature request related to a problem? Please describe.**
Attempting to map MIDI CC knobs on multiple keyboards to same CC event is difficult

**Describe the solution you'd like**
Expand the 'm' MIDI display in the status bar to include channel, CC, and value information (or note information)

**Describe alternatives you've considered**
Web UI MIDI log

**Additional context**
This is a little difficult when there are multiple events. The simple case of determining what a single knob, slider etc. is mapped to from the UI would be extremely useful and improve my workflow.

**Comment by riban-bw** [comment]
I am closing this issue because this can be achieved with MIDI Log and it is challenging to show all MIDI messages (too many changes).
