### ISSUE TITLE
Midifilter rules: Allow blocking of entire channel

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-ui#303]
**Is your feature request related to a problem? Please describe.**
I want to block certain channels so that they are not being processed or forwarded through the filter. Currently this can only done by creating a long ruleset to block each event type for the channel.

**Describe the solution you'd like**
If a channel descriptor is provided without any arguments, the rule is applied to all event types on this channel.
Example: IGNORE CH#2 would block the entire channel zynthian/zynthian-ui#122. Should this syntax not be possible, then I propose the use of wildcards: IGNORE CH#2 *

**Describe alternatives you've considered**
Use a custom mididings script instead of the Zynthian MIDI filter.

**Comment by jofemodo** [comment]
I just extended the Filter Rule System so you can set rules like this:

    IGNORE CH#2
    IGNORE CH#2,5,8
    IGNORE CH#4:7

And also like this:

    MAP CH#2 => CH#4
    MAP CH#2,9 => CH#4,13
    MAP CH#2:4 => CH#4:6

Please, update and test ...
