### ISSUE TITLE
Keyboard split

### ISSUE THREAD

**Issue by filippo-devecchi** [zynthian/zynthian-ui#305]
In zynthian is possibile to layering sound but sometime is very useful to partition the keyboard and split it. 
I think that a simple solution could be  this: 
in stagemode, leaving the feature of cloning midi to another midi channel but applying a property NOTE RANGE low and up midi note. 
So the plugin will sound only if the note is in that key range if the range is not matched no sound is trasmitted but the midi message could be route to another channel. 
In this way you can split all the key matching every situation live or studio situation jamming with looping . 
In the lower registry you can use a bass synth with arp pluing in the middle the piano with string layer (for eg.) and in the upper a lead part. 
Last request is using octave transpose in the sound. The reason is because when you split in hi range some sound could noyt be usefull so drop down or up (1 or 2) octave will be usefull for some sound.

**Comment by jofemodo** [comment]
Hi @filippo-devecchi !

I just committed the implementation for this task, but as a "layer option". Simply update and bold-click a layer. You should see a "Note Range" option ...

![zynthian_ui_note_range](https://user-images.githubusercontent.com/834765/101311968-eecfc680-3852-11eb-88f4-9f5026821c6f.png)
 
Enjoy!

**Comment by jofemodo** [comment]
I just improved a little bit, including the halftone transpose in the new Note Range modal:

![zynthian_ui_note_range](https://user-images.githubusercontent.com/834765/101349392-9669ea80-388d-11eb-9ee2-0089407b923d.png)

Enjoy!
