### ISSUE TITLE
Error loading snapshot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#307]
**Describe the bug**
Starting zynthian_gui from command line shows error loading snapshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. ssh to zynthian
2. Stop existing instance of zynthian
3. Start zynthian from command line

**Expected behaviour**
Zynthian starts with no errors.

**Actual behaviour**
Error displayed:
```
ERROR:zynthian_gui_layer.load_snapshot: Invalid snapshot: 'int' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 1247, in load_snapshot
    self.set_transpose(snapshot['transpose'])
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 470, in set_transpose
    zyncoder.lib_zyncoder.set_midi_filter_halftone_trans(i, tr_status[i]['halftone_trans'])
TypeError: 'int' object is not subscriptable
```

**Setup:**

HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: RBPi Headphones
Display: WaveShare 7 HDMI+GPIO 1024x600
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 6% (261M/3906M)
SD Card: 36% (9.5G/28G)
Temperature: 29.0ºC

SOFTWARE
zyncoder: master (aa91afe)
zynthian-ui: master (8e99583)
zynthian-sys: master (bc10bf0)
zynthian-data: master (ccf5d53)
zynthian-webconf: master (fa805d7)

**Comment by jofemodo** [comment]
It's fixed on afeceb2712fad433a9875e6990dab398385f0131
