### ISSUE TITLE
Headphone only audio output does not show in ALSA Mixer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#316]
**Describe the bug**
If a Zynthian is configured to use RBPi Headphones for audio output there is no ALSA control available.

**To Reproduce**
1. Configure Audio to use Soundcard: Rbpi Headphones
2. Edit "Mixer Controls" to add Headphones
3. Exit and return to Audio configuration in webconf and observe that Mixer Controls has returned to "Headphone Left,Headphone Right".
4. Restart Zynthian and navigate to ALSA Mixer

**Expected behaviour**
ALSA Mixer contains a level control for headphones

**Actual behaviour**
ALSA Mixer is empty.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: RBPi Headphones
Display: WaveShare 7 HDMI+GPIO 1024x600
Wiring: DUMMIES
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 18% (706M/3906M)
SD Card: 40% (11G/28G)
Temperature: 45.0ºC

SOFTWARE
zyncoder: master (aa91afe)
zynthian-ui: master (26b3bfb)
zynthian-sys: master (4ee88ca)
zynthian-data: master (336eadc)
zynthian-webconf: master (0587018)

**Additional context**
If a different soundcard is selected then headphones enabled within Zynthian Admin menu a separate "Headphone" control is added to ALSA Mixer. This should also be possible for headphone only configuration.

**Comment by jofemodo** [comment]
Hi @riban!
I just fixed this issue on 5e724cf.
Please, test and confirm.
