### ISSUE TITLE
Feature request: Test Midi input

### ISSUE THREAD

**Issue by FinlandAndy** [zynthian/zynthian-ui#33]
The admin screen has a feature to test midi which plays a midi file. It would be good to have a feature to test that midi input is working. Then it would be useful when connecting up keyboards & control surfaces.

It could identify usb midi devices with  aconnect -i   then show midi messages with aseqdump -p 

It might be tricky to handle multiple interfaces, but it would make life easier :-)

**Comment by jofemodo** [comment]
Although "alsa" tools can't be used, as Zynthian is a "100% jackd animal", it's a good idea.
Let me think about it ;-)

**Comment by jofemodo** [comment]
It's being addressed by:
https://github.com/zynthian/zynthian-webconf/issues/42#
