### ISSUE TITLE
Note command 59 is used twice

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#347]
**Describe the bug**
In Zynthian User Guide is a list with midi note commands.

No 59 is used twice for snapshot- & layer-commands

**Comment by jofemodo** [comment]
I changed the note for SWITCH_LAYER_LONG, from 59 to 68.

**Comment by Mickinator** [comment]
Hi Jose,
thank you!
Keep healthy
Micki



Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Note command 59 is used twice (#347)
Datum: 01.03.2021, 13:42 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

I changed the note for SWITCH_LAYER_LONG, from 59 to 68.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/347#issuecomment-787920332> 
, or unsubscribe
