### ISSUE TITLE
Include key-range (transposing/split) info into the ZS3s

### ISSUE THREAD

**Issue by bigmalletman** [zynthian/zynthian-ui#357]
**Is your feature request related to a problem? Please describe.**
Currently, layer transposition is not part of subsnapshot. In order to have multiple instruments with different keys, you must either change instruments and change the layers transposition manually or you need to add midi-fx transposition to each subsnapshot. (There may be other ways as well).

**Describe the solution you'd like**
Subsnapshots would include the layer transposition/split details.

**Describe alternatives you've considered**
Currently, I add midi-fx transposition to each subsnapshot.

**Additional context**
Discourse for this feature request: https://discourse.zynthian.org/t/per-instrument-transposition/5560
I have a work around that seems to work for my needs, but it was suggested that I create a feature request.

**Comment by jofemodo** [comment]
I's done. Please, update and test.

**Comment by bigmalletman** [comment]
I discovered this issue in testing this feature.
https://github.com/zynthian/zynthian-issue-tracking/issues/396

**Comment by bigmalletman** [comment]
I also discovered this more-urgent issue in testing this feature.
https://github.com/zynthian/zynthian-issue-tracking/issues/397
