### ISSUE TITLE
Always allow saving snapshot and never hide save menu

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-ui#364]
Zynthian only allows saving snapshots when it detects a change. My suggestion would be to drop this change detection in favour of always being able to save. The change detection has caused me more grief (I did changes, but could not save), and it is confusing when the save menu just disappears.
As an alternative the save menu could appear in italics or otherwise marked when Zynthian detects a change, but the saving is always allowed.

**Comment by riban-bw** [comment]
There is now a context menu for snapshots which allows saving and naming (save as).
