### ISSUE TITLE
Adding an effect to an existing layer does not offer presets

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#371]
**Describe the bug**
When adding an effects layer, e.g. MIDI effect you are offered any presets for the effect but adding the effect to an existing layer does not offer presets.

**To Reproduce**
1. Add a synth layer
2. Add a MIDI effect to the existing synth layer, e.g. MIDI Multi-Chord

**Expected behaviour**
The presets for the MIDI effect are offered.

**Actual behaviour**
The presets for the MIDI effect are not offered.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 19% (382M/1939M)
SD Card: 72% (9.5G/14G)
Temperature: 45.0ºC

SOFTWARE
zyncoder: testing (d852c8f)
zynthian-ui: testing (cb456cc)
zynthian-sys: add_riban_lv2_plugins (1e39efc)
zynthian-data: testing (194fd59)
zynthian-webconf: testing (b64c737)

**Additional context**
This is particularly irksome for effects that have lots of settings, e.g. the MIDI Multi-Chord effect has 36 settings of which 24 need to be set for it to be effective. Using the presets can be very useful for such effects. Also the behaviour is inconsistent and hence unexpected.

**Comment by jofemodo** [comment]
I just committed a fix for this. It also enables the "FX presets" entry on the layer options menu.

Regards,
