### ISSUE TITLE
Midi test duplicates menu on exit

### ISSUE THREAD

**Issue by kanaida2** [zynthian/zynthian-ui#372]
**Describe the bug**
Midi test duplicates menu on exit.

**To Reproduce**
Click midi test
Exit

**Expected behavior**
Back to the admin menu

**Screenshots**

**Setup:**
 - SD-image
 - custom raspberry pi 4b
 - latest software

**Additional context**

**Comment by jofemodo** [comment]
A fix has been pushed to testing branch. Please, test and confirm.
