### ISSUE TITLE
Cannot save snapshots

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#375]
**Describe the bug**
After pushing Bold snapshot (Load snapshot) and short snapshot (save snapshot)
the save snapshot-Window does nt show "New Snapshot" so I cannot save.

**To Reproduce**
After pushing Bold snapshot (you see Load snapshot) and short snapshot (you see save snapshot)
the save snapshot-Window does nt show "New Snapshot"

**Expected behavior**
there needs to be the possibility to save a new snapshot

**Setup:**
![grafik](https://user-images.githubusercontent.com/55761217/112757526-58363980-8fea-11eb-89bf-f1dc4c77053b.png)

**Additional context**
I don't use the encoder knobs but note-commands on channel 16.
Bold Snapshot = 72
Short Snapshot = 71
The save snapshot also doesn't work when I'm using the mouse.

**Comment by jofemodo** [comment]
OK! You have several snapshot banks! I found the problem and just pushed a fix to testing branch. Please test and confirm.

Thanks!
