### ISSUE TITLE
Test Branch: can't select layers properly. 

### ISSUE THREAD

**Issue by MrDham** [zynthian/zynthian-ui#376]
**Describe the bug**
Testing UI on test branch after fix of zynthian/zynthian-ui#360. 
I can't select any other layer than the 1st created one. 

**To Reproduce**
1. Create 2 layers
2. **Select** layer 1 -> You are in Layer 1  "control"
3. **Back** until you are in layer list
2. **Select** layer 2 -> You are in Layer 1  "control"
4. Push **Layer** -> You stay in layer 1 "control"

**Expected behavior**
2. **Select** layer 2 -> You are in **Layer 2**  "control"
4. Push **Layer** -> You change of layer "control"

**Screenshots**
I can get if required

**Setup:**
 - SD-image
Build Date: 2020-09-05 

 - Hardware Config
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+
Display: PiScreen 3.5 (v2)
Wiring: MCP23017_EXTRA
GPIO Expander: MCP23017
 
- Software Version
 zyncoder: testing (d852c8f)
zynthian-ui: testing (1894310)
zynthian-sys: testing (9b6ead4)
zynthian-data: testing (194fd59)
zynthian-webconf: testing (33699a7)

**Additional context**
Test branch.

**Comment by jofemodo** [comment]
I just pushed a fix on testing branch,
This bug has been introduced by recent changes. It should be tested carefully and merged on stable with next hotfixes.
