### ISSUE TITLE
Adding a virtual "favourites" bank folder for synths

### ISSUE THREAD

**Issue by Pastitas** [zynthian/zynthian-ui#381]
**Is your feature request related to a problem? Please describe.**
The problem is the favorites list (currently bound to bold press snap) seems to be easily forgotten and, because of that, It's less often used.

**Describe the solution you'd like**
I'd like a bank folder at the top of the preset list called "Favorites", maybe even separated by a "------" from the rest, where all the favorites from a synth appear. This would maintain the current list access via the bold press, just add another list for enhancing usability. 

This might even allow for another "default" folder like the favorites one with some community voted presets to show what the synth is capable of.

**Describe alternatives you've considered**
Another alternative would be adding some kind of text that reminds the user of the hidden favorites menu, but this seems unpractical and more complex than just presenting said list as a folder

*

**Comment by Pastitas** [comment]
So quick, It works beautifully!
I'm trying to understand the changes in the code, you just added a new bank which comes from the favorites list, right?

**Comment by jofemodo** [comment]
In fact code is simpler like this. Having a virtual "favorites" bank is more straight forward than having the "view only favorites" mode, that was implemented before.
