### ISSUE TITLE
Handling of empty snapshot does not consider sequences

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#387]
**Describe the bug**
There are various workflows within Zynthian which detect whether there are any layers and behave accordingly, e.g. saving current state on shutdown. These workflows do not consider whether the user has created sequences without any layers, e.g. using Zynthian purely as a step sequencer for external devices.

**To Reproduce**
1. CLEAN ALL
2. Add a step sequence
3. Shut down gracefully
4. Start up and check for sequence

**Expected behaviour**
Sequence is restored after restart.

**Actual behaviour**
Sequence is lost after restart.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 19% (381M/1939M)
SD Card: 36% (9.6G/29G)
Temperature: 47.0ºC
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on
- SOFTWARE
zyncoder: testing (26ffaed)
zynthian-ui: testing (5f2aac5)
zynthian-sys: testing (624ec00)
zynthian-data: testing (f71259d)
zynthian-webconf: testing (6636592)

**Additional context**
It may be advantageous to have a function that checks for configuration which includes sequences, layers, etc. then call this to detect if the device is clean rather than just check the quantity of layers. This would be extensible for any other configurations that may identify the unit as unclean.

**Comment by jofemodo** [comment]
I just removed the checking for "num of layers" when saving last state snapshot and also when showing the "Clean All" option on main menu. Please, test & confirm.
