### ISSUE TITLE
Add playhead time (HH:MM:SS) to and ability to rewind/advance to Audio Recorder screen

### ISSUE THREAD

**Issue by gr0k-net** [zynthian/zynthian-ui#390]
**Is your feature request related to a problem? Please describe.**
It would be super useful to have an hh:mm:ss ticker on the Audio Recorder screen during playback and recording.

It would be even cooler if we could use the encoders to skip forwards and backwards during playback.

**Describe the solution you'd like**
On the Audio Recorder screen, on the right hand side below the volume control or logo is a spare spot for another control. The play head timer might work well there.

With regards to reversing and advancing, my original proposal in [another thread ](https://github.com/zynthian/zynthian-ui/issues/388) proposed using the select encoder for this, but this would prevent the ability to toggle loop status and overdub recordings. 

Perhaps there is a convention somewhere else in the Zynthian for using the layer or back encoders? Both appear to be unused on the Audio Recorder screen. Whichever encoder is used, it might work like this:

- turning it right advances the playhead 1% per click (or other appropriate value, perhaps working with speed/velocity of encoders if possible?)
- turning it left to rewind the playhead 1% per click (or other appropriate value, perhaps working with speed/velocity of encoders if possible?

**Describe alternatives you've considered**
As an alternative to the playhead timer being in the bottom right, it could also replace the 'Audio Recorder' title during playback and recording.

Alternatively, the interface could be flipped so the list is on the right, then:
- the select encoder continues to operate as it currently does,
- the layer encoder would control the volume, with the volume widget being next to it on the top left
- the back encoder would control fast forward / rewind, with the playhead timer being next to it on the bottom left

**Additional context**
The playhead timer will be useful for both playback and recording, and the ability to advance backwards and forwards during playback will allow scanning through longer captures to help idenfity significant sections, or jump quickly between them once found.

**Comment by riban-bw** [comment]
See issue https://github.com/zynthian/zynthian-issue-tracking/issues/136 for similar request with some suggested implementation ideas.
