### ISSUE TITLE
Pianoteq 6.2 isn't picked up by jack autoconnect method because of hardcoding

### ISSUE THREAD

**Issue by hammerandtongs** [zynthian/zynthian-ui#41]
zynthian-ui/zynautoconnect/zynthian_autoconnect.py

Adding "Pianoteq62" to engine_list fixes the issue (for now).

**Comment by Jonnie-Cache** [comment]
I'm not sure what @jofemodo has in mind for this code long-term, but I have submitted a pull request that adds Pianoteq 6.2 and also adapts the UI appropriately based on the version of Pianoteq actually installed.

#45
