### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by le51** [zynthian/zynthian-ui#414]
Hi, 
![image](https://user-images.githubusercontent.com/1586762/146654913-b9f2c163-a201-4484-8783-dc94e61e1323.png)

Hardware config is ok, Jackd is up and running, but Zynthian UI fails to start:
>./zynthian.sh: line 156: 4561 Segmentation fault ./zynthian_gui.py

[Maybe something related on Discourse](https://discourse.zynthian.org/t/custom-3-5-display-no-ui/5355/12).

**Comment by davidfurey** [comment]
This might be the same issue as https://github.com/zynthian/zyncoder/pull/38

**Comment by jofemodo** [comment]
Could you update and try now?

**Comment by le51** [comment]
Hi sorry for late reply ...
Yes everything is okay now
Thks
