### ISSUE TITLE
New No/Yes button easy to press NO on lower functions (Reboot etc)

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#49]
The location of the No button makes it very eay for this to be selected when you press functions like reboot.
It looks like a failure because effectively you select No unintentionally.

Relocate No Button?

**Comment by mheidt** [comment]
The NO is left, isn't it?
The right lower button is the Select button, which makes it YES Freitag, 17 August 2018, 08:46vorm. +02:00 von Chris Lyon  notifications@github.com :

**Comment by jofemodo** [comment]
I agree with @mheidt. The "NO" button is perfectly OK ;-)
@wyleu, could you be more explicit about your use case? Are you using the touch interface?

**Comment by wyleu** [comment]
Using it via mouse on hdmi screen. It's quite difficult to reboot this
way.  It wasn't until I worked out what was going on I thought it wasn't
rebooting. Ignore if it's just another wyleu whinge

**Comment by jofemodo** [comment]
@mheidt, perhaps we could add an option for disabling the "confirmation dialog" ?
It should be located in the "User Interface" tab ...

**Comment by jofemodo** [comment]
Please @wyelu, explain the problem a little bit more in depth. I would like to understand the issue too ... ;-)

**Comment by wyleu** [comment]
Don't worry. It's a familiarity issue on my part.
False alarm
