### ISSUE TITLE
have a ui for footpedals

### ISSUE THREAD

**Issue by RustoMCSpit** [zynthian/zynthian-ui#495]
https://github.com/zynthian/zynthian-hw/issues/11

the above is my suggestion for a new product and if youre going to do it youre going to need a ui, hence this issue

**Comment by riban-bw** [comment]
We do not track issues here. If there is a bug or feature request for zynthain-ui then add a full request using the template at https://github.com/zynthian/zynthian-issue-tracking. Detail is important to allow developers to understand the issue.
