### ISSUE TITLE
Delete .../pianoteq6/presets_cache.json after .ptq install

### ISSUE THREAD

**Issue by josephfh** [zynthian/zynthian-ui#50]
After using the web config to install the free bells.ptq I had to delete this file in order to see the presets for the new items (for example, _Church bells_).

`rm /zynthian/zynthian-my-data/pianoteq6/presets_cache.json` 

https://www.pianoteq.com/free_stuff

**Comment by jofemodo** [comment]
Sorry, I can't reproduce. It's working perfectly for me.
Did you install the PTQ file on a updated system? Did you update your software after burning your SD image? Remember that it's the first thing you have to do ;-)
