### ISSUE TITLE
Pianoteq User Presets not as tuple

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#63]
in get_user_presets there is

user_presets.append((preset_path,None,preset_title,None))

means, it is a tupel

but the preset list itself contains mainly arrays, which means that in 
generate_presets_midimapping you get this

INFO:root:('My Presets/Steinway D Prelude (444)', None, 'MY/Prelude (444)', None)
DEBUG:root:None
ERROR:root:'tuple' object does not support item assignment
INFO:root:['Steinway D Prelude', None, 'Prelude', None]

We should fix this, when we have the new pianoteq api

**Comment by jofemodo** [comment]
Could you test if it works now? ;-)

Thanks!

**Comment by mheidt** [comment]
I don't see the error anymore...thumbs up
