### ISSUE TITLE
File /etc/dbus-1/system-local.conf resets on update.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-ui#64]
When a software update is run, the file /etc/dbus-1/system-local.conf is returned to a default state, but under certain USB input situations the default alsa device is NOT 0 but 1 (for instance Behringer UCA-222) where an entry in the file should be 

```
# replace the line
allow own=“org.freedesktop.ReserveDevice1.Audio0”
 # with
allow own=“org.freedesktop.ReserveDevice1.Audio1”
```

thus the Zynth will not boot ( fails on jackd) 

Could we add another magic flag for this in webconf and all stations in between so that the value persists across updates?

**Comment by jofemodo** [comment]
OK! It's already fixed.

**Comment by jofemodo** [comment]
Fixed with https://github.com/zynthian/zynthian-sys/commit/01604adbd177a37a4b5d80f8dbc7568e08e9cfce
