### ISSUE TITLE
MIDI Recorder playback issues

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#76]
Select a MIDI capture and click the SELECT knob. Playback commences and the item changes to green.
Playback stops with a buzz at end of recording.
Item remains green after playback has completed.
During playback the top item says, "Start Recording" so there is no way to stop playback.

**Comment by riban-bw** [comment]
MIDI Recorder page has wrong quantity of options - scroll down list of captures and you can scroll past the end.

**Comment by jofemodo** [comment]
It's fixed now ;-)
