### ISSUE TITLE
Feature request: Ability to delete recordings

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#77]
It would be advantageous to allow deletion of audio and MIDI recordings from the UI, e.g. by bold press to select a context menu offering such options as:

- Delete
- Move (e.g. to USB)

**Comment by wyleu** [comment]
Agreed it will help with quick and effective file handling but I suggest rename is left to webconf

**Comment by jofemodo** [comment]
Only "delete" by now .... with bold-click
