### ISSUE TITLE
UI stucks after several program change from sequencer

### ISSUE THREAD

**Issue by ivan1071** [zynthian/zynthian-ui#8]
Hi, as described to jose on zynthian forum, i experienced a UI freeze (or unresponsive) if there are several program changes messages over a multichannel snapshot. 
Tried with 3 or 4 channels only.
This happens not immediately, but after a bunch of times. not always the same time. a bit difficult to reproduce with precision.. The fact is Zynthian continues to respond to midi messages from sequencer, but everything on UI is stuck. (hardware encoders included).
Now i'm trying to figure out if it's a fault of one of engines, (i used fluidsynth together with zynaddsubfx) or even sending CC changes makes the same freeze.

At this moment i'm avoiding to use setBFree (not yet midi channel separable) or MOD UI, which needs a separate setup with multichannel, built from web interface, and not in zynthian itself

**Comment by jofemodo** [comment]
Please, can you confirm if this bug is currently preset?

**Comment by ivan1071** [comment]
I checked, and seems fixed now :), UI continues working

**Comment by jofemodo** [comment]
OK! I close the Issue ;-)

**Comment by jofemodo** [comment]
Probably fixed by 0a840fea998d13d48b4e109e6b3f038c4091699a
