### ISSUE TITLE
Remove all effects can remove instrument instead

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#81]
Add a Synth Layer.
Add an effect to the synth.
In "Detailed Layer List" bold press on the effect.
Select "Remove All Effects".
Expected behaviour: The effect is removed.
Actual behaviour: The synth is removed.

**Comment by jofemodo** [comment]
Yes. "Detailed layer list" is a "quick & dirty" implementation. It should be removed or improved ...

**Comment by jofemodo** [comment]
OK! It should be fixed now ... although "detailed list" implementation is far from nice ;-)

**Comment by jofemodo** [comment]
Could you confirm if it's solved for you?

Thanks!

**Comment by riban-bw** [comment]
Sorry - this isn't working.

- From Layer page, create a NEW Synth Layer: FluidSynth: MIDI CH #1: FluidR3 GM: Yamaha Grand Piano
- From Layer page, bold press on synth and Add Effect: Auto phaser
- From Layer page, short press LAYER button to show Detailed Layer List
- From Detailed Layer List, bold press on 1#JV/Auto phaser: Remove Effect
Expected behaviour: Effect removed from chain.
Actual behaviour: Zynthian locks up with busy icon perpetually animated.

Running Zynthian from command line I see a warning when selecting "Remove effect":

> WARNING:root:zynthian_gui.zyncoder_read() => unordered types: NoneType() >= int()

**Comment by jofemodo** [comment]
Try now ;-)

**Comment by jofemodo** [comment]
Ups! Sorry! I didn't push the last commit on this ... i will do it tomorrow.
