### ISSUE TITLE
Default engine effects values

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#88]
The default values for effects in engines is:

- reverb = 64
- chorus = 2

(There are others.) It may be more appropriate to have these defaults set to zero to avoid colouring of sound when first opening an engine. Certainly the first thing I do when I create a new layer is to reset both of these values.

**Comment by jofemodo** [comment]
I think it could be fine ... but perhaps it should be discussed in the forum to see what community thinks about?
