### ISSUE TITLE
ZynAddSubFX does not run with jack configured with 512 frames

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#91]
- Configure Jack with 512 frames using the -p 512 option
- Add news ZynAddSubFX layer
Zynthian hangs! This cause lots of delay due to ZynAddSubFX being my default patch so I could not start up Zynth to diagnose. Too little time left today to investigate further but wanted to report so it can be investigated.

**Comment by mheidt** [comment]
https://github.com/zynthian/zynthian-ui/issues/65

**Comment by jofemodo** [comment]
But 512 is a power of 2. It should be working fine ...
Although it's not a priority (default configuration with 256 works OK with all engines), it should be investigated ...

**Comment by benru89** [comment]
I have found a solution for this, I know it is not at all your priority to have the onboard card working properly but maybe this problem can arise also with other configurations for other cards. ZynAddSubFx needs to be run with the same buffer size as jackd. ZynAddSubFx runs by defaut with a 256 buffer so it crashes when jackd is configured with another buffer size.
![image](https://user-images.githubusercontent.com/1123559/78459158-68595880-76b7-11ea-932c-d7c46d0208a7.png)
Adding -b 512 to the ZynAddSubFx initialization fixes it. Of course you would like to do it in a proper way, passing a parameter so it always matches what has been configured for jack.

**Comment by jofemodo** [comment]
OK! It should be fixed now! Update and test, please...

**Comment by jofemodo** [comment]
Thanks for the tip, @benru89 ;-)
