### ISSUE TITLE
Feature request: ZS3 option per snapshot

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-ui#98]
I would like to have a snapshot which is Fluidsynth on all MIDI channels with General MIDI soundfont and all GM program changes mapped as default to allow use as a GM sound module. I would further like to change to a different snapshot and take advantage of the sub-snapshot feature.
Currently the ZS3 option is global for the whole device requiring change in the web interface. It would be advantageous to configure ZS3 within each Snapshot.

**Comment by jofemodo** [comment]
Good point! I will implement it ASAP ;-)

**Comment by jofemodo** [comment]
This is probably adressed on #113 ...
