### ISSUE TITLE
Deleting effect layers in multilayer environment

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#99]
from jerash:

I’ve had an issue while adding and removing effects on a layer
have a preset with two layers (chanels 5 and 6 on my preset, using generators)
take the second layer with one effect added
add a new effect (once added you’re on the controller screen)
go back (you’re on layer screen)
bold press select, go down to your newly added effect
bold press select, delete the effect
then you’re back to the effect screen from the other layer

I had a simular behaviour when playing with cloned effect layers.
I will retest after this is fixed.

**Comment by jerash** [comment]
This fix is ok for me
